Css two column layout -Tim Chiang
tychiang922/c0522-code-solutions pull request #20
Opened 2022-05-13 20:24 UTC by tychiang922

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/103610490/168384171-a722ed4d-af3f-4cb7-ad23-cd79adc3e6de.png">

2022-05-14 22:59 UTC, codingcodymiller requested changes
Hey Tim! A couple notes:
1. Your line spacing on the subheader in the first row and the text in the second row is incorrect as compared to the example.
2. There is too much space between the columns horizontally in the second row.

Please revise and submit a new screenshot with your revision.

2022-05-14 23:32 UTC, tychiang922 commented
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/103610490/168451274-f4fa4abf-7f1a-4bce-9849-d2e8fbf488e7.png">

2022-05-14 23:32 UTC, codingcodymiller requested changes
Your line spacing is still incorrect

2022-05-14 23:33 UTC, tychiang922 commented
> Your line spacing is still incorrect

Line spacing as in line height for the subheader and text-content?

2022-05-14 23:37 UTC, tychiang922 commented
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/103610490/168451383-e4ed579b-5107-47ef-b174-4d02d4408c94.png">

2022-05-15 05:17 UTC, tychiang922 commented
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/103610490/168458313-5f0d8ba6-7984-4aa0-89be-7f947a1f26d8.png">

2022-05-15 19:38 UTC, codingcodymiller requested changes

2022-05-15 19:38 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +            <div class="col-2-1fourth">
`col-2-1fourth`
I don't see a rule for this class.

2022-05-15 19:38 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +            <div class="col-2-3fourth pt-30">
`col-2-3fourth`
I don't see a rule for this class.

2022-05-16 17:49 UTC, tychiang922 commented
![image](https://user-images.githubusercontent.com/103610490/168652811-2fe3ed72-a99c-474f-81e5-741320dd95d9.png)

2022-05-16 22:28 UTC, codingcodymiller approved these changes
Nice work!!

2022-05-16 22:58 UTC, merged